set_property SRC_FILE_INFO {cfile:e:/20230426/parallel_IO_2018.2_for_class/parallel_IO_2018.2_for_class.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc rfile:../../../../../parallel_IO_2018.2_for_class.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc id:1 order:EARLY scoped_inst:U0} [current_design]
set_property SRC_FILE_INFO {cfile:e:/20230426/parallel_IO_2018.2_for_class/parallel_IO_2018.2_for_class.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc.xdc rfile:../../../../../parallel_IO_2018.2_for_class.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc.xdc id:2 order:EARLY scoped_inst:U0} [current_design]
set_property SRC_FILE_INFO {cfile:e:/20230426/parallel_IO_2018.2_for_class/parallel_IO_2018.2_for_class.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc rfile:../../../../../parallel_IO_2018.2_for_class.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc id:3 order:EARLY scoped_inst:U0} [current_design]
set_property SRC_FILE_INFO {cfile:E:/20230426/parallel_IO_2018.2_for_class/parallel_IO_2018.2_for_class.runs/design_1_microblaze_0_0_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:4} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:7 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 33.333 -name Dbg_Clk [get_ports Dbg_Clk]
set_property src_info {type:SCOPED_XDC file:1 line:8 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 33.333 -name Dbg_Update [get_ports Dbg_Update]
set_property src_info {type:SCOPED_XDC file:1 line:9 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_clock_groups -asynchronous -group [get_clocks Dbg_Clk]
set_property src_info {type:SCOPED_XDC file:1 line:10 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_clock_groups -asynchronous -group [get_clocks Dbg_Update]
set_property src_info {type:SCOPED_XDC file:1 line:11 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_clock_groups -logically_exclusive -group [get_clocks Dbg_Clk] -group [get_clocks Dbg_Update]
set_property src_info {type:SCOPED_XDC file:2 line:55 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 10.000 -name Clk [get_ports Clk]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_ports Reset]
set_property src_info {type:XDC file:4 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells U0]
