# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/20230426/parallel_IO_2018.2_for_class/parallel_IO_2018.2_for_class.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_2/design_1_mdm_1_2.xci
# IP: The module: 'design_1_mdm_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/20230426/parallel_IO_2018.2_for_class/parallel_IO_2018.2_for_class.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_2/design_1_mdm_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mdm_1_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/20230426/parallel_IO_2018.2_for_class/parallel_IO_2018.2_for_class.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_2/design_1_mdm_1_2_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mdm_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/20230426/parallel_IO_2018.2_for_class/parallel_IO_2018.2_for_class.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_2/design_1_mdm_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mdm_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/20230426/parallel_IO_2018.2_for_class/parallel_IO_2018.2_for_class.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_2/design_1_mdm_1_2.xci
# IP: The module: 'design_1_mdm_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/20230426/parallel_IO_2018.2_for_class/parallel_IO_2018.2_for_class.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_2/design_1_mdm_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mdm_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/20230426/parallel_IO_2018.2_for_class/parallel_IO_2018.2_for_class.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_2/design_1_mdm_1_2_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mdm_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/20230426/parallel_IO_2018.2_for_class/parallel_IO_2018.2_for_class.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_2/design_1_mdm_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mdm_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
